### ISSUE TITLE
Maven java.io.FileNotFoundException for elasticsearch-cloud-kubernetes-6.1.2.zip

### ISSUE THREAD

**Issue by hmacias** [fabric8io/elasticsearch-cloud-kubernetes#119]
I tried installing this plugin's 6.1.2 version in a container running docker.elastic.co/elasticsearch/elasticsearch:6.1.2. The following exception is thrown:

`[elasticsearch@d4e70f2404c5 ~]$ ./bin/elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:6.1.2
-> Downloading io.fabric8:elasticsearch-cloud-kubernetes:6.1.2 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/6.1.2/elasticsearch-cloud-kubernetes-6.1.2.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:326)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:371)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:213)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:204)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
Caused by: java.io.FileNotFoundException: https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/6.1.2/elasticsearch-cloud-kubernetes-6.1.2.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:325)
	... 10 more
[elasticsearch@d4e70f2404c5 ~]$`

**Comment by smileisak** [comment]
Some issue. Can someone build the `6.1.2` release plz ?

**Comment by jcantrill** [comment]
I dont have rights to push to maven, best I can do for you: https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-6.1.2

**Comment by jcantrill** [comment]
@maxandersen Help me help you....

**Comment by hmacias** [comment]
May I ask why this was closed if https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/6.1.2/elasticsearch-cloud-kubernetes-6.1.2.zip is still returning HTTP 404?

**Comment by pdlug** [comment]
Having the same issue, agree this shouldn't have been closed.

**Comment by jcantrill** [comment]
@hmacias @pdlug See comment https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/119#issuecomment-370951248  If you wish to reopen thats your prerogative but I am unable to say when it will be available in maven

**Comment by hmacias** [comment]
Thank you @jcantrill
