### ISSUE TITLE
Failure to validate self-signed SSL certificate

### ISSUE THREAD

**Issue by pires** [fabric8io/elasticsearch-cloud-kubernetes#15]
The service-account has been configured and provided to the pods.

```
[2015-06-14 18:50:06,164][WARN ][io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider] [Conan the Barbarian] Exception caught during discovery javax.ws.rs.ProcessingException : javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://10.100.0.1:443/api/v1beta3/namespaces/default/endpoints/elasticsearch-discovery: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://10.100.0.1:443/api/v1beta3/namespaces/default/endpoints/elasticsearch-discovery: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:557)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:539)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:676)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy29.endpointsForService(Unknown Source)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.getNodesFromKubernetesSelector(K8sUnicastHostsProvider.java:123)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.buildDynamicNodes(K8sUnicastHostsProvider.java:106)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:313)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2$1.doRun(UnicastZenPing.java:232)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://10.100.0.1:443/api/v1beta3/namespaces/default/endpoints/elasticsearch-discovery: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1364)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1348)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:624)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:674)
	... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:275)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1563)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1533)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1335)
	... 16 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
	... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 39 more
[2015-06-14 18:50:06,211][INFO ][cluster.service          ] [Conan the Barbarian] new_master [Conan the Barbarian][8LwgUksNRAujqNy2TCHuEQ][elasticsearch-master-houon][inet[/10.244.68.7:9300]]{data=false, master=true}, reason: zen-disco-join (elected_as_master)
[2015-06-14 18:50:06,222][INFO ][node                     ] [Conan the Barbarian] started
[2015-06-14 18:50:06,356][INFO ][gateway                  ] [Conan the Barbarian] recovered [0] indices into cluster_state
```

**Comment by jimmidyson** [comment]
Try an (undocumented) env var KUBERNETES_TRUST_CERT=true

**Comment by pires** [comment]
@jimmidyson thank you. I have a patch that fixes SSL validation by using the token provided to the pod. Would you be interested in it - it removes the need for Fabric8 API - or looking for a specific solution?

**Comment by jimmidyson** [comment]
I thought the token provided to the pod for a service account was just a bearer token file? How does that solve cert validation? Interested to see it.

**Comment by pires** [comment]
@jimmidyson nevermind, you are right. Anyway, do you see a better solution?

**Comment by jimmidyson** [comment]
Try to push https://github.com/GoogleCloudPlatform/kubernetes/issues/7648...

**Comment by pires** [comment]
Just did, thanks.

**Comment by pires** [comment]
@jimmidyson it seems I can query the API but the service account is not working and the plug-in execution is unauthorized.

The controller
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-master
  namespace: default
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearch-master
        image: pires/elasticsearch:master
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
```

The service-account
```
$ kubectl get serviceaccounts
NAME            SECRETS
default         1
elasticsearch   1
```

The logs
```
[2015-06-14 20:15:47,480][WARN ][io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider] [Iron Man 2020] Exception caught during discovery javax.ws.rs.WebApplicationException : HTTP 401 Unauthorized

javax.ws.rs.WebApplicationException: HTTP 401 Unauthorized

	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:25)
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:16)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy29.endpointsForService(Unknown Source)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.getNodesFromKubernetesSelector(K8sUnicastHostsProvider.java:123)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.buildDynamicNodes(K8sUnicastHostsProvider.java:106)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:313)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2$1.doRun(UnicastZenPing.java:232)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-14 20:15:47,493][INFO ][cluster.service          ] [Iron Man 2020] new_master [Iron Man 2020][Nj2Sqz0-TcSf_cX6b1UZOQ][elasticsearch-master-lrybt][inet[/10.244.68.9:9300]]{data=false, master=true}, reason: zen-disco-join (elected_as_master)
[2015-06-14 20:15:47,508][INFO ][node                     ] [Iron Man 2020] started
[2015-06-14 20:15:47,546][INFO ][gateway                  ] [Iron Man 2020] recovered [0] indices into cluster_state
```

**Comment by jimmidyson** [comment]
@pires Can you please exec into the container & check that the service account token automounted at `/var/run/secrets/kubernetes.io/serviceaccount/token` exists & is readable?

**Comment by pires** [comment]
@jimmidyson seems so.

```
$ kubectl exec elasticsearch-master-36rfd -- ls -las /var/run/secrets/kubernetes.io/serviceaccount/token
     4 -r--r--r--    1 root     root           860 Jun 15 11:32 /var/run/secrets/kubernetes.io/serviceaccount/token
```

**Comment by pires** [comment]
@jimmidyson anything else I can do to figure this out? Thank you.

**Comment by jimmidyson** [comment]
Sorry @pires - was really busy last week. Let me take a look now.

On your side, can you try to see if the service account token works with curl - something like:

`curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes/api/v1/namespaces/default/pods`

**Comment by pires** [comment]
```
$ kubectl exec elasticsearch-master-36rfd -- whoami
root

$ kubectl exec elasticsearch-master-36rfd -- curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes/api/v1/namespaces/default/pods
cat: /var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0    206      0 --:--:-- --:--:-- --:--:--   224
Unauthorized

$ kubectl exec elasticsearch-master-36rfd -- ls -las /var/run/secrets/kubernetes.io/serviceaccount/token
     4 -r--r--r--    1 root     root           860 Jun 15 11:32 /var/run/secrets/kubernetes.io/serviceaccount/token
```

@jimmidyson any hint why `ls` shows the file exists, but `curl` complains it does not?

>cat: /var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory

**Comment by pires** [comment]
```
$ kubectl exec elasticsearch-master-36rfd -- cat /var/run/secrets/kubernetes.io/serviceaccount/token
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImVsYXN0aWNzZWFyY2gtdG9rZW4tYjhyZHUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWxhc3RpY3NlYXJjaCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjE2ZTZlZWRmLTEzNTItMTFlNS05ODBmLTA4MDAyNzcxOGM2NCIsInN1YiI6InNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6ZWxhc3RpY3NlYXJjaCJ9.bhNtUqdXwitXy7b16tOVS_QoG2A4ChrtsGKdpXXcEdhSBq3AqFop2-sJE4LR0rpJqsFIpxyok89UP4mdvamcSXdpCGTxHJ1IqTATnqqP8OIIXJBz5Sx3t_QZn9WmP__3a-0U14b3A8H_C71XUCLFKUGyFEEh-BQKSFErmp-_aUsiijniULw3cFVevS5sU7NNf615NnYRC3MmZJBB7eZPCm3uxypxYRS1NN5CBKGrSMgu1w1x4GDjCNZgkaqf8B2mZE-FxV37d6voDmH5uFyw646lqVkfsSk4tfeUNMsJqzT-riHl1op0W8_TgCEO4lnL5Wtv_JvGBfrJ8pwFiWLYDw
```

**Comment by pires** [comment]
This worked @jimmidyson 

```
$ kubectl exec elasticsearch-master-36rfd -- curl -k -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImVsYXN0aWNzZWFyY2gtdG9rZW4tYjhyZHUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZWxhc3RpY3NlYXJjaCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjE2ZTZlZWRmLTEzNTItMTFlNS05ODBmLTA4MDAyNzcxOGM2NCIsInN1YiI6InNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6ZWxhc3RpY3NlYXJjaCJ9.bhNtUqdXwitXy7b16tOVS_QoG2A4ChrtsGKdpXXcEdhSBq3AqFop2-sJE4LR0rpJqsFIpxyok89UP4mdvamcSXdpCGTxHJ1IqTATnqqP8OIIXJBz5Sx3t_QZn9WmP__3a-0U14b3A8H_C71XUCLFKUGyFEEh-BQKSFErmp-_aUsiijniULw3cFVevS5sU7NNf615NnYRC3MmZJBB7eZPCm3uxypxYRS1NN5CBKGrSMgu1w1x4GDjCNZgkaqf8B2mZE-FxV37d6voDmH5uFyw646lqVkfsSk4tfeUNMsJqzT-riHl1op0W8_TgCEO4lnL5Wtv_JvGBfrJ8pwFiWLYDw" https://kubernetes/api/v1/namespaces/default/pods
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "85677"
  },
  "items": [
    {
      "metadata": {
        "name": "elasticsearch-master-36rfd",
        "generateName": "elasticsearch-master-",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/pods/elasticsearch-master-36rfd",
        "uid": "261c032e-1352-11e5-980f-080027718c64",
        "resourceVersion": "699",
        "creationTimestamp": "2015-06-15T11:32:05Z",
        "labels": {
          "component": "elasticsearch",
          "role": "master"
        },
        "annotations": {
          "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"elasticsearch-master\",\"uid\":\"261a0978-1352-11e5-980f-080027718c64\",\"apiVersion\":\"v1\",\"resourceVersion\":\"522\"}}"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "storage",
            "emptyDir": {}
          },
          {
            "name": "elasticsearch-token-b8rdu",
            "secret": {
              "secretName": "elasticsearch-token-b8rdu"
            }
          }
        ],
        "containers": [
          {
            "name": "elasticsearch-master",
            "image": "pires/elasticsearch:master",
            "ports": [
              {
                "name": "transport",
                "containerPort": 9300,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "KUBERNETES_TRUST_CERT",
                "value": "true"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "storage",
                "mountPath": "/data"
              },
              {
                "name": "elasticsearch-token-b8rdu",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "ClusterFirst",
        "serviceAccount": "elasticsearch",
        "nodeName": "172.17.8.102"
      },
      "status": {
        "phase": "Running",
        "conditions": [
          {
            "type": "Ready",
            "status": "True"
          }
        ],
        "hostIP": "172.17.8.102",
        "podIP": "10.244.31.3",
        "startTime": "2015-06-15T11:34:45Z",
        "containerStatuses": [
          {
            "name": "elasticsearch-master",
            "state": {
              "running": {
                "startedAt": "2015-06-15T11:34:45Z"
              }
            },
            "lastState": {},
            "ready": true,
            "restartCount": 0,
            "image": "pires/elasticsearch:master",
            "imageID": "docker://07c6a52741c7a3741c83b207c29c0b42d0dc769e8680db2df4c2cc33b1a3a0b9",
            "containerID": "docker://2315790f25ef34357d1a314383255bb0c01dfcdff918449d3d32736318c8e27b"
          }
        ]
      }
    },
    {
      "metadata": {
        "name": "kube-dns-y9gd1",
        "generateName": "kube-dns-",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/pods/kube-dns-y9gd1",
        "uid": "07d6eaa8-1351-11e5-980f-080027718c64",
        "resourceVersion": "85655",
        "creationTimestamp": "2015-06-15T11:24:04Z",
        "labels": {
          "k8s-app": "kube-dns",
          "kubernetes.io/cluster-service": "true"
        },
        "annotations": {
          "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"kube-dns\",\"uid\":\"ff150941-1350-11e5-980f-080027718c64\",\"apiVersion\":\"v1\",\"resourceVersion\":\"47\"}}"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "default-token-vhsa2",
            "secret": {
              "secretName": "default-token-vhsa2"
            }
          }
        ],
        "containers": [
          {
            "name": "etcd",
            "image": "gcr.io/google_containers/etcd:2.0.9",
            "command": [
              "/usr/local/bin/etcd",
              "-listen-client-urls",
              "http://127.0.0.1:2379,http://127.0.0.1:4001",
              "-advertise-client-urls",
              "http://127.0.0.1:2379,http://127.0.0.1:4001",
              "-initial-cluster-token",
              "skydns-etcd"
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "default-token-vhsa2",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent"
          },
          {
            "name": "kube2sky",
            "image": "gcr.io/google_containers/kube2sky:1.7",
            "args": [
              "-kube_master_url=http://172.17.8.101:8080",
              "-domain=cluster.local"
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "default-token-vhsa2",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent"
          },
          {
            "name": "skydns",
            "image": "gcr.io/google_containers/skydns:2015-03-11-001",
            "args": [
              "-machines=http://localhost:2379",
              "-addr=0.0.0.0:53",
              "-domain=cluster.local",
              "-nameservers=8.8.8.8:53,8.8.4.4:53"
            ],
            "ports": [
              {
                "name": "dns",
                "containerPort": 53,
                "protocol": "UDP"
              },
              {
                "name": "dns-tcp",
                "containerPort": 53,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "default-token-vhsa2",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "livenessProbe": {
              "exec": {
                "command": [
                  "/bin/sh",
                  "-c",
                  "nslookup kubernetes.default.cluster.local localhost \u003e/dev/null"
                ]
              },
              "initialDelaySeconds": 30,
              "timeoutSeconds": 5
            },
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "Default",
        "serviceAccount": "default",
        "nodeName": "172.17.8.102"
      },
      "status": {
        "phase": "Running",
        "conditions": [
          {
            "type": "Ready",
            "status": "True"
          }
        ],
        "hostIP": "172.17.8.102",
        "podIP": "10.244.31.2",
        "startTime": "2015-06-15T11:26:21Z",
        "containerStatuses": [
          {
            "name": "skydns",
            "state": {
              "running": {
                "startedAt": "2015-06-15T11:26:21Z"
              }
            },
            "lastState": {},
            "ready": true,
            "restartCount": 0,
            "image": "gcr.io/google_containers/skydns:2015-03-11-001",
            "imageID": "docker://791ddf327076e0fd35a1125568a56c05ee1f1dfd7a165c74f4d489d8a5e65ac5",
            "containerID": "docker://2ca15babbbf05824de6027cc3aef3d8ccf2b3e494338f28a312063dd560d43b1"
          },
          {
            "name": "kube2sky",
            "state": {
              "running": {
                "startedAt": "2015-06-15T11:26:07Z"
              }
            },
            "lastState": {},
            "ready": true,
            "restartCount": 0,
            "image": "gcr.io/google_containers/kube2sky:1.7",
            "imageID": "docker://916d1b51d1d581e73ef889187e598e5fd7ab2e440fb35955c2b3f8e353b79fa2",
            "containerID": "docker://9dc65316759c3622f34c9af4f73066bdcef50d335a6c29631d72de5fdff00d95"
          },
          {
            "name": "etcd",
            "state": {
              "running": {
                "startedAt": "2015-06-15T11:25:45Z"
              }
            },
            "lastState": {},
            "ready": true,
            "restartCount": 0,
            "image": "gcr.io/google_containers/etcd:2.0.9",
            "imageID": "docker://b6b9a86dc06aa1361357ca1b105feba961f6a4145adca6c54e142c0be0fe87b0",
            "containerID": "docker://a25b37a3cefa737b03f48a13eaf189724f239f6485a407aec734b11357187a1e"
          }
        ]
      }
    }
  ]
100  9245    0  9245    0     0   124k      0 --:--:-- --:--:-- --:--:--  132k
```

**Comment by pires** [comment]
I'm running Kubernetes `0.19.0`.

**Comment by pires** [comment]
No update on this?
