### ISSUE TITLE
Permissions when running as non-root user

### ISSUE THREAD

**Issue by dermidgen** [fabric8io/elasticsearch-cloud-kubernetes#18]
I believe this may have something to do with the new security context, but I'm having a real tough time getting this working with ES 2.0.  Initially https://github.com/fabric8io/kubernetes-client was having trouble connecting due to an inability to read `/var/run/secrets/kubernetes.io/serviceaccount/*`.  This used to work fine when ES ran under root; no longer. I resorted to exporting `KUBERNETES_AUTH_TOKEN`, `KUBERNETES_CERTS_CLIENT_DATA`, `KUBERNETES_AUTH_TRYSERVICEACCOUNT=false`, `KUBERNETES_AUTH_TRYKUBECONFIG=false` to bypass the fs permissions issues. Now I'm getting nailed by:
```
[2015-11-17 17:57:59,605][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Robert Bruce Banner] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch. Cause: access denied ("java.net.NetPermission" "getProxySelector")
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch. Cause: access denied ("java.net.NetPermission" "getProxySelector")
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:245)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:182)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:173)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:472)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:105)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:27)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:81)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:316)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2.doRun(UnicastZenPing.java:230)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.net.ProxySelector.getDefault(ProxySelector.java:94)
	at com.squareup.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java:614)
	at com.squareup.okhttp.Call.<init>(Call.java:48)
	at com.squareup.okhttp.OkHttpClient.newCall(OkHttpClient.java:595)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:180)
	... 11 more
```

**Comment by pires** [comment]
@jimmidyson I think we need something like https://github.com/elastic/elasticsearch/blob/master/plugins/discovery-gce/src/main/plugin-metadata/plugin-security.policy, do we not?

**Comment by jimmidyson** [comment]
Probably :) PR very welcome.

**Comment by pires** [comment]
See also https://github.com/elastic/elasticsearch/blob/d81993026112b4557c5d387b4348a1d0f18865b8/docs/plugins/authors.asciidoc#java-security-permissions

@dermidgen want to give a try at this? I'm too busy this week.

**Comment by dermidgen** [comment]
@pires  @jimmidyson I will see what I can come up with; thanks

**Comment by dermidgen** [comment]
Gosh; I'm really having some trouble running local maven tests. @jimmidyson can you run tests against a PR for me?

**Comment by jimmidyson** [comment]
We haven't got any tests for this 2.0 version yet! Sorry was cobbled together & loads changed - PR welcome for that too ;)

**Comment by dermidgen** [comment]
I sure would love to, but I was struggling a bit to get my environment going. @pires has a branch https://github.com/pires/elasticsearch-cloud-kubernetes/tree/2.0.0 that he's been working on and it looks like he's been trying to get testing going as well.

**Comment by danielschonfeld** [comment]
I think we might need more than ReflectionPermission.  We're running into the same problems as @dermidgen is running + also getting permission denied when trying to open either the `~.kube/config` file or the `ca.crt` or `token` files.

Example:

```
[2015-11-18 20:33:30,690][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [es-rack-1-c11aw] Exception caught during discovery: access denied ("java.io.FilePermission" "/home/elasticsearch/.kube/config" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/elasticsearch/.kube/config" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.isRegularFile(Files.java:2229)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:17)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:37)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:82)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.client(KubernetesAPIServiceImpl.java:56)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:27)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:81)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:316)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2.doRun(UnicastZenPing.java:230)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jimmidyson** [comment]
I think we should make the security policy as strict as we can but still work. Right now we need to be able to read files (any really as `KUBECONFIG`, etc can be set via env vars which we can't use in security policies AFAIK) & `getProxySelector`.

How does that sound?

**Comment by pires** [comment]
@dermidgen unfortunately that branch of mine is borked. I screwed up cause I hadn't merged with latest upstream changes. When I tried to do so, I got into a mess I couldn't get out of with the time availability I have at this moment.

@jimmidyson sounds like a plan!

**Comment by jimmidyson** [comment]
I'm looking at this now... docs are terrible tbh so trying to figure it out... getting somewhere slowly.

**Comment by jimmidyson** [comment]
Well I've hit a brick wall with this one. Not sure now if plugins can set security policies in 2.0, might have to wait for 2.1 which seems to have support for that.

Of course if anyone else can figure this out that would be awesome.

**Comment by pires** [comment]
@jimmidyson any hints from the Elasticsearch community? We can try and get someone to enlighten our path  - not sure who, though.

**Comment by jimmidyson** [comment]
Not sure either.

One option would be to disable security manager for 2.0 & reenable for 2.1 when it's released & we have a working security policy?

**Comment by pires** [comment]
Why not? Seems a better choice than not supporting 2.0.

Anyway, regarding `FilePermission` could it be https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_plugin_and_packaging_changes.html#_symbolic_links_and_paths?

**Comment by jimmidyson** [comment]
It could be but I'm not sure what the path property would be... Also considering that files can be specified via environment variables I think we're going to have to go with a reasonably loose security policy anyway.

**Comment by jimmidyson** [comment]
Well I got further by disabling the security manager (adding `security.manager.enabled: false` to `elasticsearch.yml`) & that's highlighted another problem so will look at fixing that in the meantime.

**Comment by jimmidyson** [comment]
I've just published version 2.0.2 of the plugin with some fixes. This will only work with security manager disabled. Please try it out & let me know if this issue can be closed.

**Comment by dermidgen** [comment]
@jimmidyson thank you so much - trying it out now.

**Comment by jimmidyson** [comment]
Don't say thanks before you've tried it ;)

**Comment by dermidgen** [comment]
Oh snap! Looks good to me!

```
[2015-11-19 16:15:04,964][INFO ][node                     ] [Phantom Eagle] version[2.0.0], pid[13], build[de54438/2015-10-22T08:09:48Z]
[2015-11-19 16:15:04,965][INFO ][node                     ] [Phantom Eagle] initializing ...
[2015-11-19 16:15:05,571][INFO ][plugins                  ] [Phantom Eagle] loaded [mapper-attachments, cloud-kubernetes], sites []
[2015-11-19 16:15:05,633][INFO ][env                      ] [Phantom Eagle] using [1] data paths, mounts [[/data (/dev/disk/by-uuid/7c2ba6f8-3e2f-49da-9d24-211659759bdb)]], net usable_space [91.3gb], net total_space [98.3gb], spins? [possibly], types [ext4]
[2015-11-19 16:15:08,266][INFO ][node                     ] [Phantom Eagle] initialized
[2015-11-19 16:15:08,272][INFO ][node                     ] [Phantom Eagle] starting ...
[2015-11-19 16:15:08,371][INFO ][transport                ] [Phantom Eagle] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2015-11-19 16:15:08,392][INFO ][discovery                ] [Phantom Eagle] myesdb/YPQzLVNAR-K0Uu8NOKjaEg
[2015-11-19 16:15:10,041][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9200
[2015-11-19 16:15:10,042][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9300
[2015-11-19 16:15:11,583][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9200
[2015-11-19 16:15:11,585][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9300
[2015-11-19 16:15:13,106][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9200
[2015-11-19 16:15:13,107][INFO ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Phantom Eagle] adding endpoint /10.56.0.10, transport_address 10.56.0.10:9300
[2015-11-19 16:15:13,151][INFO ][cluster.service          ] [Phantom Eagle] new_master {Phantom Eagle}{YPQzLVNAR-K0Uu8NOKjaEg}{127.0.0.1}{127.0.0.1:9300}{master=true}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2015-11-19 16:15:13,206][INFO ][http                     ] [Phantom Eagle] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2015-11-19 16:15:13,207][INFO ][node                     ] [Phantom Eagle] started
[2015-11-19 16:15:13,211][INFO ][gateway                  ] [Phantom Eagle] recovered [0] indices into cluster_state
```

**Comment by jimmidyson** [comment]
Looks like a gremlin in there though. Could you share your Kubernetes manifest? Also looks like your binding to localhost only - this is a change in ES 2.0 I think - try adding `network.host: 0.0.0.0` to bind to all interfaces otherwise things might not work quite right.

**Comment by pires** [comment]
@dermidgen did you add the `privileged` stuff to the pod spec?

**Comment by jimmidyson** [comment]
Why do you need that?

**Comment by pires** [comment]
@jimmidyson because of memory allocation permissions for `elasticsearch` user inside the container. See https://github.com/pires/docker-elasticsearch/issues/7

**Comment by dermidgen** [comment]
@pires I did add privileged to my rc. Take note that the parameter moved to securityContext and cannot be set on the container anymore in v1.1. @jimmidyson I believe you mentioned you were on a custom Kubernetes cluster; if you're running v1.0+ you can run privileged with the parameter set on the container. For those running on Google Container Engine, your cluster _must_ be running Kubernetes v1.1+ to get privileged containers.

@jimmidyson - good catch, thank you - will update `network.host`

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-kubernetes
  labels:
    component: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearch-kubernetes
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: gcr.io/../elasticsearch-kubernetes:latest
        env:
        - name: KUBERNETES_AUTH_TRYKUBECONFIG
          value: "false"
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
```

**Comment by jimmidyson** [comment]
So closing this now. Thanks for all your input.

**Comment by dermidgen** [comment]
@pires @jimmidyson - thanks for the help!

**Comment by pires** [comment]
@dermidgen thanks for bringing this up and thank you once more @jimmidyson for your amazing fixing skills. I'm going to update the official docs after some more tests.

**Comment by danielschonfeld** [comment]
Is setting `discovery.zen.minimum_master_nodes:2` in elasticsearch.yml detrimental to this plugin? I'm getting an insanely weird error and this is about the only thing I can think of.

Otherwise have followed everything mentioned above

The error is:
```
[2015-11-19 18:53:16,709][WARN ][http.netty               ] [es-rack-1-5pgc6] Caught exception while handling client http traffic, closing connection [id: 0x2b211e6f, /10.244.17.5:37147 => /10.244.56.3:9200]
java.lang.IllegalArgumentException: invalid version format: INTERNAL:DISCOVERY/ZEN/UNICAST8ﾲ￐^ES.KUBECLUSTER.AZUREES-RACK-1-DOC2DCVHCFBILQBQGIHCHHKUCLG
                                                                                                                                                      10.244.17.5
                                                                                                                                                                 10.244.17.5
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:94)
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pires** [comment]
@dermidgen what was the fix?
```
- name: KUBERNETES_AUTH_TRYKUBECONFIG
          value: "false"
```

**Comment by jimmidyson** [comment]
No that is totally unrelated. It looks like the service you're using is multi-port including both the http & transport ports - is that right?

**Comment by jimmidyson** [comment]
What it looks like is it's trying to use the http port for cluster comms - you need to separate out the services.

**Comment by danielschonfeld** [comment]
That's true. My service is both. Should I separate them each to their own ?
With 9300 used for cluster comms?

**Comment by jimmidyson** [comment]
@danielschonfeld Yeah that's the best way to do it. This discovery uses the service endpoints which is a Cartesian product of endpoint addresses x ports. What I tend to do is use a headless service (i.e. one without a cluster IP) for cluster comms (port 9300) & a normal service for client (http) comms.

**Comment by dermidgen** [comment]
@pires the fix is to add `security.manager.enabled: false` to `elasticsearch.yml`

The following is more specific to your docker-elasticsearch-kubernetes.  Since we run under the user elasticsearch but without a home dir - there's no ~/.kube/config to be found. This parameter tells `kubernetes-client` not to try that, but use the service account cert and token from `/var/run/secretes/kubernetes.io/serviceaccount/`.
```
- name: KUBERNETES_AUTH_TRYKUBECONFIG
          value: "false"
```

Also for docker-elasticsearch-kubernetes I added `privileged` so that we can run `ulimit` and allow memlock.
```
securityContext:
          privileged: true
```

Both are irrelevant to this thread. For this thread the solution is to disable the security manager so that the plugin has permissions to read the filesystem and access the networking stack.

**Comment by danielschonfeld** [comment]
@jimmidyson you're right, works like a charm now! Thank you much!

**Comment by pires** [comment]
@dermidgen I don't need the following and it works with my descriptors: ```
- name: KUBERNETES_AUTH_TRYKUBECONFIG
          value: "false"
```

**Comment by dermidgen** [comment]
@pires interesting!! When I was doing that it was trying to hit /home/elasticsearch/.kube/config - I will try again

**Comment by jimmidyson** [comment]
@dermidgen that env var should be unnecessary as the file won't exist & so will just be ignored. This is on the proviso that you run with security manager turned off in Elasticsearch.

**Comment by dermidgen** [comment]
@jimmidyson YUP! That's what it was - with security manager it barfs on permissions to the path - and doesn't get as far as ignoring it. With security manager turned off - everything is back to normal.

**Comment by jimmidyson** [comment]
Ah cool. I'll try to get it working with security manager but there's no docs on it in 2.0. Have opened an issue at elastic/elasticsearch#14880
