### ISSUE TITLE
ES 2.1 plugin has permission issues to %user.home%/elasticsearch/.kube/config

### ISSUE THREAD

**Issue by anil-g** [fabric8io/elasticsearch-cloud-kubernetes#23]
I have been trying to use the plugin for ES 2.1.0 but when I start the container, I get the error below:
[2015-12-15 00:30:28,049][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Freakmaster] Exception caught during discovery: access denied ("java.io.FilePermission" "/home/elasticsearch/.kube/config" "read")

java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/elasticsearch/.kube/config" "read")
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
at java.security.AccessController.checkPermission(AccessController.java:884)
at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)

What I understood is that the plugin is using user's home directory for storing kube config. What I don't understand is that even when I run as the same user, it fails. Permission denied. 
I tried on my mac as well as a docker image. All the same. It has no effect when I reset my $HOME to my installation folder. It always points to %USER.HOME% and permission gets denied.

**Comment by jimmidyson** [comment]
You need to run with security manager disabled - see https://github.com/fabric8io/elasticsearch-cloud-kubernetes/blob/master/elasticsearch.yml#L20 for the setting. I'll add this to the readme.

Plugins will only be able to update security policy from 2.2 it seems - see https://github.com/elastic/elasticsearch/issues/14880 for more details.

**Comment by jimmidyson** [comment]
Closing now as no feedback. If this is still a problem please reopen.
